#!/bin/bash

# Automated Component Audit Report Generator
# Technical Enablement Agent - Design Token Compliance Checker

echo "🔍 Aurorion Teams Component Audit Report"
echo "========================================"
echo "Date: $(date)"
echo ""

# Count total files
echo "📊 PROJECT OVERVIEW:"
echo "Total files to audit: $(find src -name "*.astro" -o -name "*.ts" -o -name "*.tsx" -o -name "*.css" | wc -l)"
echo ""

# Hardcoded color detection
echo "🚨 HARDCODED COLOR VIOLATIONS:"
echo "Scanning for hex colors (#), rgb(), rgba(), hsl(), hsla()..."
HARDCODED_COUNT=$(rg "#[0-9a-fA-F]{3,6}|rgb\(|rgba\(|hsl\(|hsla\(" --type-add 'astro:*.astro' --type-add 'styles:*.css' -t astro -t styles -t ts --no-heading | wc -l)
echo "Total hardcoded color instances: $HARDCODED_COUNT"
echo ""

if [ $HARDCODED_COUNT -gt 0 ]; then
    echo "🔍 FILES WITH HARDCODED COLORS:"
    rg "#[0-9a-fA-F]{3,6}|rgb\(|rgba\(|hsl\(|hsla\(" --type-add 'astro:*.astro' --type-add 'styles:*.css' -t astro -t styles -t ts --no-heading --count-matches | head -10
    echo ""
fi

# Design token usage
echo "✅ DESIGN TOKEN USAGE:"
TOKEN_COUNT=$(rg "var\(--" --type-add 'astro:*.astro' --type-add 'styles:*.css' -t astro -t styles -t ts --no-heading | wc -l)
echo "Design token instances: $TOKEN_COUNT"
echo ""

# Component priority matrix
echo "📋 HIGH PRIORITY COMPONENTS (Most hardcoded colors):"
rg "#[0-9a-fA-F]{3,6}" --type-add 'astro:*.astro' -t astro --no-heading --count-matches | sort -t: -k2 -nr | head -5
echo ""

# Accessibility patterns
echo "♿ ACCESSIBILITY PATTERNS:"
echo "aria-* attributes found: $(rg "aria-" --type-add 'astro:*.astro' -t astro --no-heading | wc -l)"
echo "role attributes found: $(rg "role=" --type-add 'astro:*.astro' -t astro --no-heading | wc -l)"
echo ""

# TypeScript coverage
echo "📝 TYPESCRIPT COVERAGE:"
echo "TypeScript files: $(find src -name "*.ts" -o -name "*.tsx" | wc -l)"
echo "JavaScript files: $(find src -name "*.js" -o -name "*.jsx" | wc -l)"
echo ""

# Component analysis
echo "🧩 COMPONENT BREAKDOWN:"
echo "Pages: $(find src/pages -name "*.astro" | wc -l)"
echo "Components: $(find src/components -name "*.astro" | wc -l)"
echo "Layouts: $(find src/layouts -name "*.astro" | wc -l)"
echo ""

# Migration readiness score
TOTAL_FILES=$(find src -name "*.astro" -o -name "*.ts" -o -name "*.tsx" -o -name "*.css" | wc -l)
if [ $TOTAL_FILES -gt 0 ]; then
    TOKEN_PERCENTAGE=$((TOKEN_COUNT * 100 / (TOKEN_COUNT + HARDCODED_COUNT)))
    echo "📈 MIGRATION READINESS SCORE: ${TOKEN_PERCENTAGE}%"
    echo "Design tokens: $TOKEN_COUNT | Hardcoded: $HARDCODED_COUNT"
else
    echo "📈 MIGRATION READINESS SCORE: Unable to calculate"
fi

echo ""
echo "🎯 NEXT STEPS:"
if [ $HARDCODED_COUNT -gt 50 ]; then
    echo "- HIGH PRIORITY: Start with files having most hardcoded colors"
    echo "- Focus on systematic component migration"
elif [ $HARDCODED_COUNT -gt 20 ]; then
    echo "- MEDIUM PRIORITY: Batch process remaining hardcoded colors"
    echo "- Implement automated validation"
else
    echo "- LOW PRIORITY: Final cleanup and validation"
    echo "- Focus on documentation and standards"
fi

echo ""
echo "Report generated by Technical Enablement Agent"
echo "========================================"