name = "astro-teams"
compatibility_date = "2024-01-15"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "aurorion-teams-local"
database_id = "local_database"

[[vectorize]]
binding = "VECTORIZE"
index_name = "aurorion-project-knowledge"

[ai]
binding = "AI"

[vars]
WEBAUTHN_RP_NAME = "Aurorion Teams"
WEBAUTHN_RP_ID = "team.homedevenv.com"
WEBAUTHN_ORIGIN = "https://team.homedevenv.com"
SITE_URL = "team.homedevenv.com"

# Environment-specific overrides
[env.local]
vars = { WEBAUTHN_RP_ID = "team.homedevenv.com", WEBAUTHN_ORIGIN = "https://team.homedevenv.com", SITE_URL = "team.homedevenv.com" }

[env.development]
vars = { WEBAUTHN_RP_ID = "team.homedevenv.com", WEBAUTHN_ORIGIN = "https://team.homedevenv.com", SITE_URL = "team.homedevenv.com" }