-- Database Indexes for Optimal Performance
-- Generated by Tester-Reviewer Agent following Victoria's performance analysis

-- Team Members Performance Indexes
CREATE INDEX IF NOT EXISTS idx_team_members_role ON team_members(role);
CREATE INDEX IF NOT EXISTS idx_team_members_status ON team_members(status);
CREATE INDEX IF NOT EXISTS idx_team_members_email ON team_members(email);
CREATE INDEX IF NOT EXISTS idx_team_members_role_status ON team_members(role, status);

-- Projects Performance Indexes  
CREATE INDEX IF NOT EXISTS idx_projects_status_priority ON projects(status, priority);
CREATE INDEX IF NOT EXISTS idx_projects_category_status ON projects(category, status);
CREATE INDEX IF NOT EXISTS idx_projects_dates ON projects(start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_projects_slug ON projects(slug); -- Already unique, but explicit index

-- Project Members Analytics Indexes
CREATE INDEX IF NOT EXISTS idx_project_members_project_status ON project_members(project_id, status);
CREATE INDEX IF NOT EXISTS idx_project_members_member_contribution ON project_members(member_id, contribution);
CREATE INDEX IF NOT EXISTS idx_project_members_project_member ON project_members(project_id, member_id);

-- Activity Logs Time-Series Indexes
CREATE INDEX IF NOT EXISTS idx_activity_logs_member_timestamp ON activity_logs(member_id, timestamp);
CREATE INDEX IF NOT EXISTS idx_activity_logs_type_timestamp ON activity_logs(type, timestamp);
CREATE INDEX IF NOT EXISTS idx_activity_logs_project_timestamp ON activity_logs(project_id, timestamp);

-- Metrics Analytics Indexes
CREATE INDEX IF NOT EXISTS idx_metrics_type_dates ON metrics(type, start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_metrics_member_type ON metrics(member_id, type);
CREATE INDEX IF NOT EXISTS idx_metrics_project_type ON metrics(project_id, type);

-- Agent Sessions Workflow Indexes
CREATE INDEX IF NOT EXISTS idx_agent_sessions_role_status ON agent_sessions(agent_role, status);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_project_timestamp ON agent_sessions(project_id, start_time);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_handoff ON agent_sessions(handoff_to, status);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_member_role ON agent_sessions(member_id, agent_role);

-- Agent Decisions Audit Indexes
CREATE INDEX IF NOT EXISTS idx_agent_decisions_session_type ON agent_decisions(session_id, decision_type);
CREATE INDEX IF NOT EXISTS idx_agent_decisions_agent_status ON agent_decisions(agent_role, status);
CREATE INDEX IF NOT EXISTS idx_agent_decisions_authority ON agent_decisions(authority_level, status);

-- Enterprise Metrics Business Indexes
CREATE INDEX IF NOT EXISTS idx_enterprise_metrics_project_category ON enterprise_metrics(project_id, metric_category);
CREATE INDEX IF NOT EXISTS idx_enterprise_metrics_type_period ON enterprise_metrics(metric_type, measurement_period);
CREATE INDEX IF NOT EXISTS idx_enterprise_metrics_dates ON enterprise_metrics(start_date, end_date);

-- Performance Metrics Technical Indexes
CREATE INDEX IF NOT EXISTS idx_performance_metrics_session_timestamp ON performance_metrics(session_id, timestamp);
CREATE INDEX IF NOT EXISTS idx_performance_metrics_timestamp ON performance_metrics(timestamp);

-- Audit Logs Security Indexes
CREATE INDEX IF NOT EXISTS idx_audit_logs_entity_type_timestamp ON audit_logs(entity_type, timestamp);
CREATE INDEX IF NOT EXISTS idx_audit_logs_security_level ON audit_logs(security_level, timestamp);
CREATE INDEX IF NOT EXISTS idx_audit_logs_event_type ON audit_logs(event_type, timestamp);
CREATE INDEX IF NOT EXISTS idx_audit_logs_agent_timestamp ON audit_logs(agent_role, timestamp);